name: learn-github-actions

on: [push]
jobs:
  learn-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install mocha --save-dev
      - run: npm install chai --save-dev
      - run: npm install istanbul --save-dev
      - run: npm run test
      - run: npm run coverage
      
